### ISSUE TITLE
Not getting any response from wit.ai

### ISSUE THREAD

**Issue by mszadko** [wit-ai/voicesdk-unreal#30]
Hi. I wrote in simmilar thread but on different repository (wit-ai/wit-unreal). I saw you added template of the project with everything set up out of the box but my issue didn't change so I guess it's not a configuration issue. 
So here is what i've done.

1.  I downloaded template project and pasted into my engine folder.
2. Created new project using mentioned template.
3. Made sure there is [Voice] bEnabled=true in engine.ini (there are 3 of those in template not sure why)
4. Opened oculus->configuration editor and made new config where I paste my server and client access tokens.
5. Made new BP class derived from AppVoiceExperience. Enabled input from player0 on it and added key event that calls ActivateVoiceInput.
6. Added print string functions to every delegate there is on VoiceEvents component.

Expected result :

1. I press T and start talking - ActivateVoiceInput returns true 
2. On partial transcription displays text from what i've spoken as in this https://www.youtube.com/watch?v=UB4Uzmw8XA8 tutorial.
3. I press T again and ActivateVoiceInput returns true again and we go to 2.

What i got

1. I press T and start talking - ActivateVoiceInput returns true 
2. I got only callbacks from events start voice input, on minimum treshold hit, stop voice input, stop due to timeout/inactivity
3. I press T again and ActivateVoiceInput returns false and i never get any wit response.

Is there any extra step that I'm missing?

**Comment by wangpingsx** [comment]
Hi mszadko, 
I will do some dig on this. There are 2 things I recommend you to check:
1. Is your microphone working ok? We have a threshold on volume, if you input volume is low, the sdk will not take any input.  Microphone issue is a bit hard for me to help. So let's check if this is micrphone issue or the sdk/network issue. I recommend you use text instead of voice, to sew if it works.  Please check here to see how I did on the sample project demo: https://github.com/wit-ai/voicesdk-unreal-samples/blob/main/readme_images/guide.gif
2. I feel you already did #1 :-)  I saw your logs from another thread.   But I found a couple of this log printed in a very short time `url=[https://api.wit.ai/message?v=20230104&q=make%20the%20cube%20red`   seems you put "make the cube red" in the text box and clicked the send button, but it cannot be executed many times in a very short time.  do you have multi player setup in your game?

![image](https://user-images.githubusercontent.com/1758819/215788692-6d2182e5-28c8-4844-83d0-252ad85acd4c.png)

**Comment by mszadko** [comment]
Hi. 
Thanks for response!
I don't have multiplayer setup. 
ad1. My mic is working fine. I testes it out with voice capture component and it mirrors my voice correctly. Also if i whistle to my microphone for more than 20seconds I get event called from VoiceEvents component about ending due to timeout instead of inactivity.
My messages got a little bit messy because I post them in different issues so I will try to sum things up. At first I followed your tutorial on youtube(the one with opening doors). It didn't work so I tried to read some more documentation. 

Then I created sample project with shapes and color, made wit.ai app with .zip folder I downloaded from readme page, set my server and client token inside config. but still pressing send button didn't change anything. I started debuging and unpinned branch node after pressing the button wheter `voice is activated ` or `request is in progress` just to execute latter nodes from this demo. It send the message from log you posted but I never got any response. I wrote more about it in this thread https://github.com/wit-ai/wit-unreal/issues/57 because it looked like GameBayoumy had same issue.

Then I returned to door example with differents version of wit.ai plugin. One from marketplace, I tried also with 1click setup from here and also downloaded some tagged releases (49.0.1) if i remember correctly but urfortunately every setup I made had same result. I could send only 1 request to wit.ai and I never got any response. So I gave out with doors and returned to sample project because it got less steps to reproduce so there was less things make wrong.

So today I followed the .gif you just send me and made the clear app. It still didn't work so I decided to follow whats happening during sending request and made this thread https://github.com/wit-ai/voicesdk-unreal-samples/issues/2. I pasted there my project and tokens for the app.

**Comment by mszadko** [comment]
SOLUTION: So it turned out that it wasn't problem with wit.ai and plugin at all. I tried to send different http request and same behaviour occured. Found this thread on forum https://forums.unrealengine.com/t/http-requests-not-working-in-plugin/446775
