### ISSUE TITLE
Compile Error when using the 3 and 4 option if instalation

### ISSUE THREAD

**Issue by devPirate01** [wit-ai/voicesdk-unreal#46]
I tried options 2, 3 and 4.
The marketplace route, crashes when enter the token from wit.ai and create a configuration.
The Manual Installation(5.3.2) way route and the 1-click route give the the following errors when compiling and won't open up unreal engine.

Using UE5.3.2

`[1/6] Compile [x64] Module.Wit.4.cpp

10>WitHttpEngineIncludes.cpp(24): Error C1083 : Cannot open include file: 'HttpThread.cpp': No such file or directory
Total time in Parallel executor: 49.20 seconds
Total execution time: 50.07 seconds
10>Microsoft.MakeFile.Targets(44,5): Error MSB3073 : The command ""F:\Program Files\Epic Games\UE_5.3\Engine\Build\BatchFiles\Build.bat" MyProjectTEST01Editor Win64 Development -Project="E:\temp\MyProjectTEST01\MyProjectTEST01.uproject" -WaitMutex -FromMsBuild" exited with code 6.
`

**Comment by IanSlatteryMeta** [comment]
`HttpThread.cpp` is an Unreal Engine file that should be included in the distribution of UE5.3.2 at `[Local UE installation folder]\Engine\Source\Runtime\Online\HTTP\Private\`. Ensure that the file has not been removed. If it is not present, a fresh install of Unreal Engine should remedy the situation.

Additionally, there have been issues with the UE5.3.2 Marketplace plugin due to a change to their underlying libraries, so ensure before trying options 3 and 4 to have the Voice SDK Marketplace plugin removed from UE5.3.

If these options do not remedy the issue, please reach out with more information regarding your setup - Operating System, MSVS Version, and any log files.

**Comment by devPirate01** [comment]
Thanks for your swift reply.
It seams the engine was installed properly I had to install the "Engine Source" from the installation options of UE5.3.2 inside epic games. Now it is working properly.
Before installing that, only the HttpThread.h has visible in the directory you specified, after installing the "Engine Source" the cpp file also appeared.
I was not aware I had to install that as well. It might be helpful to other develops to include this in the installation process.
 
![image](https://github.com/wit-ai/voicesdk-unreal/assets/117528215/3cc0e4fc-c4a7-4069-bda9-7ca6c5595671)
![UEWithoutEngineSource](https://github.com/wit-ai/voicesdk-unreal/assets/117528215/4893e741-68a9-4092-a112-96e849444312)
![UEWithEngineSource](https://github.com/wit-ai/voicesdk-unreal/assets/117528215/9a8e41bb-8b52-4e29-b411-d86407bcbd82)
